Rails.application.routes.draw do
  get 'baskets/index'
  get 'baskets/show'
  get 'baskets/new'
  get 'baskets/create'
  get 'baskets/edit'
  get 'baskets/update'
  get 'baskets/destroy'
  get 'products/index'
  get 'products/new'
  get 'products/create'
  get 'products/edit'
  get 'products/update'
  get 'products/destroy'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/create'
  get 'restaurants/edit'
  get 'restaurants/update'
  get 'restaurants/destroy'
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
